# Keys for LocalizationManger to use in source code: MIT License
# @author Vladimir Petrenko
@tool
class_name LocalizationKeys

const ATTACK_BUMPERS = "ATTACK_BUMPERS"
const RAMP_BUMPERS = "RAMP_BUMPERS"
const ENTER_RAMP = "ENTER_RAMP"
const HYPERSPACE = "HYPERSPACE"
const REBOUND = "REBOUND"
const RETURN_LANE = "RETURN_LANE"
const OUT_LANE = "OUT_LANE"
const REENTRY_LANE = "REENTRY_LANE"
const ANY_TARGET = "ANY_TARGET"
const UPGRADE_ATTACK = "UPGRADE_ATTACK"
const BOOSTER_TARGET_BANK = "BOOSTER_TARGET_BANK"
const ANY_WORMHOLE = "ANY_WORMHOLE"
const REMOTE_ATTACK_BUMPER = "REMOTE_ATTACK_BUMPER"
const ANY_LANE = "ANY_LANE"
const FLAG = "FLAG"
const MISSION_COMPLETED = "MISSION_COMPLETED"
const GAME_DESIGNER = "GAME_DESIGNER"
const GAME_DEVELOPER = "GAME_DEVELOPER"
const MUSIC_ARTIST = "MUSIC_ARTIST"
const SFX_ARTIST = "SFX_ARTIST"
const ART_DESIGNER = "ART_DESIGNER"
const TRY_AGAIN = "TRY_AGAIN"
const SHOW_LEADERBOARD = "SHOW_LEADERBOARD"
const MAIN_MENU = "MAIN_MENU"
const EXIT = "EXIT"
const START = "START"
const SETTINGS = "SETTINGS"
const CREDITS = "CREDITS"
const _GRAPHICS_ = "_GRAPHICS_"
const _SOUND_ = "_SOUND_"
const _GAMEPLAY_ = "_GAMEPLAY_"
const DISPLAY_MODE = "DISPLAY_MODE"
const VSYNC = "VSYNC"
const WINDOW_RESOLUTION = "WINDOW_RESOLUTION"
const SHADER_PALETTE = "SHADER_PALETTE"
const WINDOW_MODE = "WINDOW_MODE"
const FULLSCREEN_MODE = "FULLSCREEN_MODE"
const BORDERLESS_WINDOW_MODE = "BORDERLESS_WINDOW_MODE"
const BORDERLESS_FULLSCREEN_MODE = "BORDERLESS_FULLSCREEN_MODE"
const PINK = "PINK"
const BLUE = "BLUE"
const GRAYSCALE = "GRAYSCALE"
const MASTER_BUS = "MASTER_BUS"
const MUSIC_BUS = "MUSIC_BUS"
const SFX_BUS = "SFX_BUS"
const APPLY_BUTTON = "APPLY_BUTTON"
const BACK_BUTTON = "BACK_BUTTON"
const PLAYER_NAME = "PLAYER_NAME"
const LANGUAGE = "LANGUAGE"
const GAMEOVER = "GAMEOVER"
const SCORE: = "SCORE:"
const GAME_PAUSED = "GAME_PAUSED"
const RESUME_BUTTON = "RESUME_BUTTON"
const LEADERBOARD = "LEADERBOARD"
const LOADING_SCORES = "LOADING_SCORES"

const KEYS = [
 "ATTACK_BUMPERS",
 "RAMP_BUMPERS",
 "ENTER_RAMP",
 "HYPERSPACE",
 "REBOUND",
 "RETURN_LANE",
 "OUT_LANE",
 "REENTRY_LANE",
 "ANY_TARGET",
 "UPGRADE_ATTACK",
 "BOOSTER_TARGET_BANK",
 "ANY_WORMHOLE",
 "REMOTE_ATTACK_BUMPER",
 "ANY_LANE",
 "FLAG",
 "MISSION_COMPLETED",
 "GAME_DESIGNER",
 "GAME_DEVELOPER",
 "MUSIC_ARTIST",
 "SFX_ARTIST",
 "ART_DESIGNER",
 "TRY_AGAIN",
 "SHOW_LEADERBOARD",
 "MAIN_MENU",
 "EXIT",
 "START",
 "SETTINGS",
 "CREDITS",
 "_GRAPHICS_",
 "_SOUND_",
 "_GAMEPLAY_",
 "DISPLAY_MODE",
 "VSYNC",
 "WINDOW_RESOLUTION",
 "SHADER_PALETTE",
 "WINDOW_MODE",
 "FULLSCREEN_MODE",
 "BORDERLESS_WINDOW_MODE",
 "BORDERLESS_FULLSCREEN_MODE",
 "PINK",
 "BLUE",
 "GRAYSCALE",
 "MASTER_BUS",
 "MUSIC_BUS",
 "SFX_BUS",
 "APPLY_BUTTON",
 "BACK_BUTTON",
 "PLAYER_NAME",
 "LANGUAGE",
 "GAMEOVER",
 "SCORE:",
 "GAME_PAUSED",
 "RESUME_BUTTON",
 "LEADERBOARD",
 "LOADING_SCORES"
]